# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rotrieve = "roblox/rotriever@0.5.12"
# rojo = "rojo-rbx/rojo@6.2.0"